FROM golang:1.21 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o pod-scaler main.go

FROM alpine:latest
COPY --from=builder /app/pod-scaler /usr/local/bin/pod-scaler
ENTRYPOINT ["pod-scaler"]
